In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
ls '/content/drive/My Drive/Script google colab/Promediar'

2.tif  3.tif  4.tif  5.tif  Promediados/


In [ ]:
import PIL
from PIL import Image
import numpy as np
import tifffile as tif
#COMENT

In [ ]:
I2=tif.imread('/content/drive/My Drive/Script google colab/Promediar/2.tif')
I2=np.array(I2,np.uint32)[:,:,0]
print (I2)
I2.shape




[[22607 24338 24759 ... 21970 21598 21066]
 [23984 25274 25501 ... 22477 22853 21799]
 [24216 24938 24175 ... 23159 22312 23279]
 ...
 [25076 22402 22307 ... 23711 23102 24060]
 [23919 21749 20837 ... 24020 23591 23973]
 [22521 21088 20771 ... 23255 23000 22267]]


(274, 414)

In [ ]:
I3=tif.imread('/content/drive/My Drive/Script google colab/Promediar/3.tif')
I3=np.array(I3,np.uint32)[:,:,0]
print (I3)
I3.shape

[[22737 24524 24788 ... 21973 21722 20939]
 [24169 25403 25404 ... 22577 22692 21377]
 [24282 24911 24173 ... 22974 22609 23348]
 ...
 [24859 22320 22294 ... 23804 23213 24095]
 [23769 21695 20860 ... 24079 23804 24025]
 [22475 21063 20992 ... 23295 23229 22241]]


(274, 414)

In [ ]:
I4=tif.imread('/content/drive/My Drive/Script google colab/Promediar/4.tif')
I4=np.array(I4,np.uint32)[:,:,0]
print (I4)
I4.shape

[[22705 24498 24887 ... 22007 21764 20958]
 [24122 25383 25349 ... 22456 22732 21569]
 [24285 24932 24193 ... 23072 22575 23384]
 ...
 [24856 22344 22360 ... 23777 23099 24070]
 [23786 21737 20925 ... 24188 23814 23967]
 [22486 21061 20959 ... 23413 23263 22254]]


(274, 414)

In [ ]:
I5=tif.imread('/content/drive/My Drive/Script google colab/Promediar/5.tif')
I5=np.array(I5,np.uint32)[:,:,0]
print (I5)
I5.shape

[[22547 24426 25021 ... 22035 21908 20963]
 [23794 25330 25699 ... 22590 22715 21591]
 [24084 24919 24282 ... 23039 22545 23344]
 ...
 [25359 22664 22409 ... 23854 23285 24050]
 [24470 22104 20848 ... 24127 23789 23923]
 [23058 21378 20659 ... 23419 23114 22291]]


(274, 414)

In [ ]:
Promedio=(I2+I3+I4+I5)/4
print(Promedio)

[[22649.   24446.5  24863.75 ... 21996.25 21748.   20981.5 ]
 [24017.25 25347.5  25488.25 ... 22525.   22748.   21584.  ]
 [24216.75 24925.   24205.75 ... 23061.   22510.25 23338.75]
 ...
 [25037.5  22432.5  22342.5  ... 23786.5  23174.75 24068.75]
 [23986.   21821.25 20867.5  ... 24103.5  23749.5  23972.  ]
 [22635.   21147.5  20845.25 ... 23345.5  23151.5  22263.25]]


In [ ]:
Promedio=np.uint16(Promedio)
print(Promedio)

[[22649 24446 24863 ... 21996 21748 20981]
 [24017 25347 25488 ... 22525 22748 21584]
 [24216 24925 24205 ... 23061 22510 23338]
 ...
 [25037 22432 22342 ... 23786 23174 24068]
 [23986 21821 20867 ... 24103 23749 23972]
 [22635 21147 20845 ... 23345 23151 22263]]


In [ ]:
Image.fromarray(Promedio).save('/content/drive/My Drive/Script google colab/Promediar/Promedio_DIAZ_M.tif',dpi=(72,72))